#!/bin/bash

export PATH="$PATH:`pwd`/node_modules/.bin"

set -e
if [ "$COCKROACH" = "" ]; then
  echo "RUNNING ALL TESTS '$COCKROACH'"
  for I in packages/*/; do
    if [[ "$PGVERSION" != "9.4" || ( "$I" != "packages/lds/" && "$I" != "packages/subscriptions-lds/" ) ]]; then
      cd $I
      npm run test
      cd -
    fi;
  done
else
  cd packages/pg-analogues/
  npm run test -- cockroach
fi;
